version: "3.9"

services:
  phpfpm:
    extends:
      file: common-services.yml
      service: php
    volumes:
      - .:/app

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "8060:5672"
      - "8061:15672"
    volumes:
      - rabbitmq:/var/lib/rabbitmq/
      - .docker/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
    networks:
      - onderwijscatalogus

  nginx:
    image: nginx:1.25-alpine
    environment:
      VIRTUAL_HOST: dev.api.onderwijscatalogus.tenes.nl
    volumes:
      - .docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - .:/app
    networks:
      - onderwijscatalogus
      - shared

  wait:
    image: waisbrot/wait
    environment:
      TARGETS: rabbitmq:5672 phpfpm:9000 mysql:3306
      TIMEOUT: 900
    networks:
      - onderwijscatalogus

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: onderwijscatalogus-dev
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 8062:3306
    volumes:
      - ./.docker/mysql/config/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ./.docker/mysql/init/:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    networks:
      - onderwijscatalogus

  neo4j:
    image: neo4j:latest
    ports:
      - 8063:7474
      - 8064:7687
    volumes:
      - neo4j_data:/data/
    environment:
      NEO4J_AUTH: none
    networks:
      - onderwijscatalogus

networks:
  onderwijscatalogus:
    driver: bridge
  shared:
    name: reverseproxy
    external: true

volumes:
  rabbitmq:
    driver: local
  neo4j_data:
    driver: local
  mysql_data:
    driver: local
